* 1
*** .1
***** .1  Give the value of each of the following expressions:
       + a. (0 + 15) / 2
          int 7
       + b. 2.0e-6 * 100000000.1
          double 200.0000002
       + c. true && false || true && true
          true
***** .2 Give the type and value of each of the following expressions:
      + a. (1 + 2.236) / 2
         double 1.618
      + b. 1 + 2 + 3 + 4.0
         double 10.0
      + 4.1 >= 4
         boolean true
      + 1 + 2 + "3"
         String "123"
***** .3 Write a program that takes three integer command-line arguments and prints
      equal if all three are equal, and not equal otherwise.
      file:ThreeEqualInts.java
***** .4 What (if anything) is wrong with each of the following statements?
      + a. if (a > b) then c = 0;
         "then" is not necessary
      + b. if a > b {c = 0;}
        need parens for boolean expression
      + c. if (a > b) c = 0;
         this is OK
      + d. if (a > b) c = 0 else b = 0;
         need braces or newline for else statement
***** .5 Write a code fragment that prints true if the double variables x and y are both
      strictly between 0 and 1 and false otherwise.
#+BEGIN_SRC Java
double x;
double y;
if ((x > 0 ) && ( x<1 )) return true;
else return false ;
#+END_SRC

***** .6 What does the following program print?
      #+BEGIN_SRC Java
int f = 0;
int g = 1;
for (int i = 0; i <= 15; i++)
{
StdOut.println(f);
f = f + g;
g = f - g;
}
inital values: f = 0 ; g = 1
loop 00: 0 f = 1; g = 0
loop 01: 1 f = 1; g = 1
loop 02: 1 f = 2; g = 1
loop 03: 2 f = 3; g = 2
loop 04: 3 f = 5; g = 3
loop 05: 5 f = 8; g = 5 
loop 06: 8 f = that_number g = 8
loop 07: that_number f = 21 g = that_number
loop 08: 21 f = 34 g = 21
loop 09: 34 f = 55 g = 34
loop 10: 55 f = 89 g = 55
loop 11: 89 f = 144 g = 89
и так далее
      #+END_SRC


***** .7 Give the value printed by each of the following code fragments:
      + a.
        #+BEGIN_SRC Java
        double t = 9.0;
        while (Math.abs(t - 9.0/t) > .001)
            t = (9.0/t + t) / 2.0;
            StdOut.printf("%.5f\n", t)
        #+END_SRC
        Output: 
        3.00009
      + b.
        #+BEGIN_SRC Java
         int sum = 0;
         for (int i = 1; i < 1000; i++)
             for (int j = 0; j < i; j++)
                 sum++;
         StdOut.println(sum);
        #+END_SRC
        Output:
        499500
      + c. 
        #+BEGIN_SRC Java
        int sum = 0;
        for (int i = 1; i < 1000; i *= 2)
            for (int j = 0; j < N; j++)
                sum++;
        StdOut.println(sum);
        #+END_SRC
        Output:
        499500
***** .8 What do each of the following print?
      + a. System.out.println('b');
        b
      + b. System.out.println('b' + 'c');
        197
      + c. System.out.println((char) ('a' + 4));
        e
***** .9 Write a code fragment that puts the binary representation of a positive integer N
      into a String s .
      
